### ISSUE TITLE
Improve envoy builds

### ISSUE THREAD

**Issue by lahabana** [kumahq/envoy-builds#43]
### Description

We have issues that blocks us from reproducible/quick builds. We should also have a weekly run to make sure it doesn't break

**Comment by lukidzi** [comment]
https://github.com/kumahq/envoy-builds/pull/48
https://github.com/kumahq/envoy-builds/pull/49
https://github.com/kumahq/envoy-builds/pull/50

changes: 
* added action that runs a script to release MacOS hosts on schedule
* fixed build for the main branch
* we don't create a separate vpc for each run, we reuse the same because of the limit of VPCs, instead I've added a terraform that creates VPC if someone removes from aws
* scheduled build-release job for main branch on Monday 6 am
* moved fips build out of linux/amd64 because it took even 3-4h to build both on the same machine
